@include('admin-centre.accounts.add')
@include('admin-centre.accounts.edit')
@include('admin-centre.accounts.permissions')
@include('admin-centre.accounts.districts')
@include('admin-centre.accounts.view')
